stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker: 20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER - p $REGISTRY_PASS

  script:
    - docker build -t kuuhaku12/hello:1.0 app/.
    - docker push kuuhaku12/hello:1.0

  deploy_gcp:
    stages: deploy_gcp

    before_script:
      - chmod 400 $SSH_KEY

    script:
      - ssh -o StrictHostKeyChecking=no -i $ $SSH_KEY gcp@SSH_SERVER "sudo rm - Rf ./<repository_name>/ && sudo git clone <gitlab_url> && cd <repository_name> && sudo chmod +x ./script.sh && ./script.sh"