apiVersion: v1
kind: Pod
metadata:
  name: mysql-prod
  labels:
    name: mysql-prod
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: "MYSQL_DATABASE"
          value: "meuBanco"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "senha123"
      ports:
        - containerPort: 3306