version: "3.8"

services:
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  kafka-producer:
    container_name: kafka-producer
    image: kafka-producer
    restart: on-failure
    build: KafkaProducer/.
    ports:
      - "8080:8080"
    environment:
      HOST: kafka
      PORT: 9092
    depends_on:
      - kafka

  kafka-consumer:
    container_name: kafka-consumer
    image: kafka-consumer
    restart: on-failure
    build: KafkaConsumer/.
    ports:
      - "8081:8081"
    environment:
      HOST: kafka
      PORT: 9092
    depends_on:
      - kafka