apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: php-backend
spec:
  selector:
    app: php
  ports:
  - targetPort: 80
    port: 80
  type: LoadBalancer