stages:
  - build

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker: 20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER - p $REGISTRY_PASS

  script:
    - docker build -t kuuhaku12/hello:1.0 .
    - docker push kuuhaku12/hello:1.0